### ISSUE TITLE
Deactivation issue

### ISSUE THREAD

**Issue by stonecrusher** [M-Reimer/togglereferrer#2]
Example page:
https://userstyles.org/styles/134069/

This page will show endless waiting spinner if
- togglereferrer is activated in about:addons **and**
- togglereferrer is deactivated via its own toolbar icon

In other constellations it works as expected.

`FF66.0.3 (64-Bit)`, `Toggle Referrer 3.0.4`, no spoofing.

**Comment by M-Reimer** [comment]
I would say what you are seeing here is not really a bug but everything works as expected.

You disabled the Referer and userstyles.org has some kind of "referer protection" in their API which causes the API to silently fail if no Referer is there.

That's why you can re-enable the Referer with just one click. There is a good chance that you have to do this from time to time while surfing.

This is the whole reason why I added the optional spoofing feature. It contains the websites that I know where some referrer spoofing is needed to use it without actually sending a valid referrer. It makes it possible for me to keep the referrer disabled all the time as my "known problematic pages" still work then.

I can take care of this page with my optional spoofing feature. Just will need some time to figure something out.

**Comment by M-Reimer** [comment]
This should do it:
https://github.com/M-Reimer/togglereferrer/commit/20184933e8c6e1a7fb964178aed167358427c610
I still have to test this a bit more before creating a new release with this change.
And this change will only help you if you enable spoofing.

**Comment by M-Reimer** [comment]
Are you actually sure that you *deactivated* the addon?
The addon is *active* if there is no red flag. Meaning that if the red flag is missing you don't send a Referrer.

**Comment by stonecrusher** [comment]
Ah ok with your addition + spoofing it should do it.

About activation and deactivation there is just a bit of confusion...
In the toolbar icon tooltip it said "Toggle Referrer (aus)" (translates to "off"). No red flag, so it is active (which I misunderstood).
If I switch it, it says "Toggle Referrer (aktiviert!)" (translates to "active!") with a red flag, so actually deactivated.

IMHO it is misleading language as the toggle couples are not on/off + activated/deactivated but "off/active" and it is not clear weather "Toggle Referrer" as a whole is active or if "Sending Referrer" is on.

No need to be extra short here, you can even make multiline tooltip: 
![2019-04-24 20_41_49-Greenshot](https://user-images.githubusercontent.com/1388389/56685134-8231a380-66d1-11e9-9d51-c24f0ec5f417.png)

That would be a small enhancement request from me. But overall: Thanks for the great extension!

**Comment by M-Reimer** [comment]
Multiline does not work on Android.
Maybe it would be best if you create a second issue for the naming topic, so we can discuss this topic there.

**Comment by M-Reimer** [comment]
BTW. Feel free to create the second issue in German language.

**Comment by M-Reimer** [comment]
Fixed in 3.1.0
